# Generated by Django 5.0.3 on 2026-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_customuser_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
