# Generated by Django 5.0.3 on 2026-03-18

import base.media
import base.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0003_customuser_is_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=base.storage_backends.public_media_storage,
                upload_to=base.media.PrefixedUUIDPath("avatars"),
                validators=[base.media.validate_image_file, base.media.validate_file_size],
            ),
        ),
    ]
