# Generated by Django 5.2.17 on 2026-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds operator authority (RBAC) to the user model.

    `default='admin'` backfills every existing row with full operator authority,
    and that is the intended behaviour rather than an oversight. The field is only
    consulted for accounts that are ALREADY operators (role admin AND is_staff), so
    every row it can affect already holds every authority today. Backfilling
    least-privilege would silently strip payout and KYC authority from whatever
    operator accounts exist, which in a pilot with one or two of them is an outage
    dressed as a security improvement. The split is opt-in per account.
    """


    dependencies = [
        ('auth_user', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ops_role',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('driver_ops', 'Driver operations'), ('finance', 'Finance'), ('admin', 'Administrator')], default='admin', help_text='Operator authority. Ignored unless the account is an operator.', max_length=20),
        ),
    ]
