# Generated by Django 5.0.3 on 2026-03-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driverearning_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
