# Generated by Django 5.0.3 on 2026-03-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driver_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.vehicle'),
        ),
    ]
