# Generated by Django 5.0.3 on 2026-03-18

import base.media
import base.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0007_driver_active_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_doc",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=base.storage_backends.private_document_storage,
                upload_to=base.media.PrefixedUUIDPath("license_docs"),
                validators=[base.media.validate_document_file, base.media.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="rc_doc",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=base.storage_backends.private_document_storage,
                upload_to=base.media.PrefixedUUIDPath("rc_docs"),
                validators=[base.media.validate_document_file, base.media.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_pic",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=base.storage_backends.public_media_storage,
                upload_to=base.media.PrefixedUUIDPath("vehicle_pics"),
                validators=[base.media.validate_image_file, base.media.validate_file_size],
            ),
        ),
    ]
