# Generated by Django 5.0.3 on 2026-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driver_last_withdrawal_at_driverearning_is_settled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for UPI payouts', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI Payout')], default='bank', max_length=20),
        ),
        migrations.DeleteModel(
            name='DriverEarning',
        ),
    ]
