# Generated by Django 5.0.3 on 2026-04-19 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_driver_upi_id_withdrawalrequest_payout_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='failure_count',
            field=models.IntegerField(default=0, help_text='Number of times payout attempt failed'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Reason for last failure', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last failure', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_mode',
            field=models.CharField(blank=True, help_text='Payout mode (UPI, bank_transfer, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_reference_id',
            field=models.CharField(blank=True, help_text='Reference ID for tracking the payout', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_status',
            field=models.CharField(blank=True, help_text='Current status from Razorpay (created, processing, processed, failed)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('upi', 'UPI Payout')], default='upi', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverUPIContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_contact_id', models.CharField(blank=True, max_length=256, null=True)),
                ('razorpay_fund_account_id', models.CharField(blank=True, max_length=256, null=True)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID stored at time of contact creation', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upi_contact', to='driver.driver')),
            ],
            options={
                'verbose_name': 'Driver UPI Contact',
                'verbose_name_plural': 'Driver UPI Contacts',
            },
        ),
    ]
