# Generated by Django 5.0.3 on 2026-04-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_withdrawalrequest_failure_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverupicontact',
            old_name='razorpay_contact_id',
            new_name='gateway_contact_id',
        ),
        migrations.RenameField(
            model_name='driverupicontact',
            old_name='razorpay_fund_account_id',
            new_name='gateway_fund_account_id',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='razorpay_payout_id',
        ),
    ]