# Generated by Django 5.0.3 on 2026-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_rename_razorpay_fields_to_generic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_status',
            field=models.CharField(blank=True, help_text='Current status from payment gateway (created, processing, processed, failed)', max_length=50, null=True),
        ),
    ]
