# Generated by Django 5.0.3 on 2026-05-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_vehicle_expiries'),
        ('ride', '0008_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fatigue_lockout_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_show', 'Rider no-show'), ('vehicle_issue', 'Vehicle issue'), ('safety', 'Safety concern'), ('personal', 'Personal'), ('other', 'Other')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='driver.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_cancellations', to='ride.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', '-created_at'], name='cancel_driver_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('end_reason', models.CharField(blank=True, default='', max_length=32)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='driver.driver')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['driver', '-started_at'], name='session_driver_recent_idx')],
            },
        ),
    ]
