# Generated by Django 5.0.3 on 2026-07-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_driver_fatigue_lockout_until_drivercancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='doc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
