# Generated by Django 5.0.3 on 2026-07-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_driver_doc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='doc_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='uploaded_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
