# Generated by Django 5.0.3 on 2026-08-26 13:15

import base.media
import base.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0018_incentivequest_driverbankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_doc_back',
            field=models.FileField(blank=True, max_length=512, null=True, storage=base.storage_backends.private_document_storage, upload_to=base.media.PrefixedUUIDPath('license_docs_back'), validators=[base.media.validate_document_file, base.media.validate_file_size]),
        ),
    ]
