# Generated by Django 5.0.3 on 2026-09-11 06:34

import base.media
import base.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0019_driver_license_doc_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fitness_doc',
            field=models.FileField(blank=True, max_length=512, null=True, storage=base.storage_backends.private_document_storage, upload_to=base.media.PrefixedUUIDPath('fitness_docs'), validators=[base.media.validate_document_file, base.media.validate_file_size]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_doc',
            field=models.FileField(blank=True, max_length=512, null=True, storage=base.storage_backends.private_document_storage, upload_to=base.media.PrefixedUUIDPath('insurance_docs'), validators=[base.media.validate_document_file, base.media.validate_file_size]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='permit_doc',
            field=models.FileField(blank=True, max_length=512, null=True, storage=base.storage_backends.private_document_storage, upload_to=base.media.PrefixedUUIDPath('permit_docs'), validators=[base.media.validate_document_file, base.media.validate_file_size]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_doc',
            field=models.FileField(blank=True, max_length=512, null=True, storage=base.storage_backends.private_document_storage, upload_to=base.media.PrefixedUUIDPath('puc_docs'), validators=[base.media.validate_document_file, base.media.validate_file_size]),
        ),
    ]
