# Generated by Django 5.0.3 on 2026-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0020_vehicle_fitness_doc_vehicle_insurance_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='doc_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
