# Generated by Django 5.2.17 on 2026-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_driver_doc_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('completed', 'Completed'), ('failed', 'Failed'), ('unresolved', 'Unresolved - provider outcome unknown')], default='pending', max_length=20),
        ),
    ]
