# Generated by Django 5.0.3 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteplace',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='favoriteplace',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
