# Generated by Django 5.0.3 on 2026-04-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20),
        ),
    ]
