# Generated by Django 5.0.3 on 2026-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_wallettransaction_idempotency_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='razorpay_order_id',
            new_name='gateway_order_id',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='razorpay_payment_id',
            new_name='gateway_payment_id',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='razorpay_signature',
            new_name='gateway_signature',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_gateway',
            field=models.CharField(choices=[('cashfree', 'Cashfree')], default='cashfree', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='txn_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=20),
        ),
    ]