# Generated by Django 5.0.3 on 2026-05-22 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0007_notification_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactional', models.BooleanField(default=True)),
                ('ride_event', models.BooleanField(default=True)),
                ('payment', models.BooleanField(default=True)),
                ('payout', models.BooleanField(default=True)),
                ('sos', models.BooleanField(default=True)),
                ('kyc', models.BooleanField(default=True)),
                ('system', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('promo', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
