# Generated by Django 5.0.3 on 2026-05-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0008_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='flagged_for_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rider',
            name='review_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='review_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
