# Generated by Django 5.0.3 on 2026-07-26 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0009_rider_flagged_for_review_rider_rating_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='scope',
            field=models.CharField(choices=[('rider', 'Rider credits (closed-loop)'), ('driver', 'Driver settlement balance')], db_index=True, default='rider', max_length=16),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user_id', 'scope'), name='wallet_unique_user_scope'),
        ),
    ]
