# Generated by Django 5.0.3 on 2026-03-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='txn_type',
            field=models.CharField(choices=[('payment', 'Payment from Rider'), ('credit', 'Credit to Driver'), ('debit', 'Debit from Wallet'), ('refund', 'Refund to Rider')], default='payment', max_length=20),
        ),
    ]
