# Generated by Django 5.0.3 on 2026-04-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transactionhistory_txn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='replaced_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='switch_reason',
            field=models.CharField(blank=True, choices=[('user_requested', 'User Requested'), ('system_error', 'System Error')], max_length=50, null=True),
        ),
    ]