# Generated by Django 5.0.3 on 2026-04-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driver_last_withdrawal_at_driverearning_is_settled_and_more'),
        ('payments', '0005_payment_replaced_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='withdrawal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='driver.withdrawalrequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('wallet', 'Wallet'), ('deferred', 'Deferred')], max_length=20),
        ),
    ]
