# Generated by Django 5.0.3 on 2026-04-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transactionhistory_withdrawal_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cashfree_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cashfree_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cashfree_payment_session_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree')], db_index=True, default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='cashfree_payment_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='cashfree_transfer_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='gateway_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='gateway_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_gateway',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cashfree', 'Cashfree')], db_index=True, default='razorpay', max_length=20),
        ),
    ]
