# Generated by Django 5.0.3 on 2026-05-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_cashfree_order_id_and_more'),
        ('ride', '0006_alter_trip_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='razorpay_payment_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('cashfree', 'Cashfree')], db_index=True, default='cashfree', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_gateway',
            field=models.CharField(choices=[('cashfree', 'Cashfree')], db_index=True, default='cashfree', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='trip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ride.trip'),
        ),
    ]
