# Generated by Django 5.2.17 on 2026-09-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_driver_doc_rejection_reason'),
        ('payments', '0010_payment_completed_unique'),
        ('ride', '0015_farepricing_trail_coverage_ratio_and_more'),
        ('rider', '0011_split_driver_settlement_wallets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('settled_at', models.DateTimeField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('native', 'Written at settlement time'), ('reconstructed', 'Reconstructed from historical facts')], db_index=True, default='native', max_length=16)),
                ('provenance_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='driver.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='ride.trip')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='rider.wallettransaction')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', '-settled_at'], name='tripsettlement_driver_idx'), models.Index(fields=['-settled_at'], name='tripsettlement_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip', 'version'), name='tripsettlement_unique_trip_version'), models.UniqueConstraint(condition=models.Q(('version', 1)), fields=('trip',), name='tripsettlement_one_original_per_trip'), models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='tripsettlement_commission_non_negative'), models.CheckConstraint(condition=models.Q(('gross_fare__gte', 0)), name='tripsettlement_gross_non_negative')],
            },
        ),
    ]
