# Generated by Django 5.0.3 on 2026-05-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_seed_phase0_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='code',
            field=models.CharField(help_text='Stable identifier, e.g. "IN-TG-HYD" or "IN-TG-HYD-AIRPORT".', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='state_code',
            field=models.CharField(blank=True, help_text='ISO 3166-2 sub-division code without the country prefix, e.g. "TG", "KA".', max_length=8),
        ),
    ]
