# Generated by Django 5.2.17 on 2026-09-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_platformsettings'),
        ('ride', '0012_triplocationpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFareShadow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shadow_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shadow_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_duration_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coverage_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trail_points', models.IntegerField(default=0)),
                ('zone_code', models.CharField(blank=True, default='', max_length=64)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=64)),
                ('rate_card_version', models.IntegerField(blank=True, null=True)),
                ('surge_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quote_source', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(default='computed', max_length=32)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fare_shadow', to='ride.trip')),
            ],
            options={
                'db_table': 'trip_fare_shadow',
                'indexes': [models.Index(fields=['observed_at'], name='fareshadow_observed_idx'), models.Index(fields=['zone_code', 'observed_at'], name='fareshadow_zone_idx'), models.Index(fields=['status'], name='fareshadow_status_idx')],
            },
        ),
    ]
