"""Service-area enforcement.

Phase-0 launches in Hyderabad only. Trips with a pickup OR drop outside
the Hyderabad metro polygon are rejected at the server before any fare
is computed, so a tampered client can't create trips in other cities.

The polygon is a rough convex hull around Greater Hyderabad Municipal
Corporation + the airport corridor — generous enough that legitimate
suburbs (Gachibowli, Madhapur, Kondapur, Kompally, LB Nagar, Uppal,
Hayathnagar, Chevella) are included and tight enough that Bangalore
or Vijayawada is not. Refine via env-driven override
`SERVICE_AREA_BBOX_OVERRIDE` if a closer fit is needed later (Phase-1
will replace this with PostGIS + per-city polygons).
"""

from typing import Tuple

from django.conf import settings
from shapely.geometry import Point, Polygon


# Rough polygon (lon, lat) around Greater Hyderabad. Generated by walking
# the GHMC boundary plus the airport corridor; intentionally generous
# (includes Shamshabad airport south, Patancheru west, Kompally north,
# Ghatkesar east).
_HYDERABAD_POLYGON_LONLAT = [
    (78.205, 17.190),  # SW — Patancheru / Lingampally
    (78.155, 17.380),  # W — Mokila
    (78.230, 17.560),  # NW — Kompally
    (78.420, 17.620),  # N — Bachupally
    (78.580, 17.580),  # NE — Medchal corridor
    (78.700, 17.480),  # E — Ghatkesar
    (78.730, 17.310),  # SE — Hayathnagar
    (78.680, 17.180),  # S — LB Nagar / Vanasthalipuram
    (78.470, 17.140),  # SSW — Shamshabad airport
    (78.330, 17.155),  # SW — Aramghar
]


def _polygon():
    """Build the polygon (cached on the module)."""
    global _CACHED_POLY
    try:
        return _CACHED_POLY  # type: ignore[name-defined]
    except NameError:
        pass
    coords = list(_HYDERABAD_POLYGON_LONLAT)
    # Env override: comma-separated lon:lat pairs, semicolon-delimited
    raw = getattr(settings, 'SERVICE_AREA_OVERRIDE', '') or ''
    if raw:
        try:
            override = []
            for pair in raw.split(';'):
                lon, lat = pair.split(',')
                override.append((float(lon), float(lat)))
            if len(override) >= 3:
                coords = override
        except Exception:
            # bad override — fall through to default
            pass
    poly = Polygon(coords)
    globals()['_CACHED_POLY'] = poly
    return poly


def is_inside_service_area(lat, lon) -> bool:
    """Return True iff (lat, lon) sits inside the operating polygon.

    Both args may be Decimal, str, or float. None or unparsable inputs
    return False so callers can treat "could not validate" the same as
    "out of area" — the safe default is to refuse.
    """
    try:
        lat_f = float(lat)
        lon_f = float(lon)
    except (TypeError, ValueError):
        return False
    if not (-90 <= lat_f <= 90 and -180 <= lon_f <= 180):
        return False
    return _polygon().contains(Point(lon_f, lat_f))


def validate_service_area(
    pickup_lat, pickup_lon, dest_lat, dest_lon,
) -> Tuple[bool, str]:
    """Validate that BOTH pickup and destination are in the polygon.

    Returns (ok, error_message). On ok=True the message is empty.
    Caller pattern:

        ok, msg = validate_service_area(p_lat, p_lon, d_lat, d_lon)
        if not ok:
            return 400 with msg
    """
    if not is_inside_service_area(pickup_lat, pickup_lon):
        return False, (
            'Pickup location is outside the SaaradhiGo service area. '
            'We currently operate within Hyderabad metro.'
        )
    if not is_inside_service_area(dest_lat, dest_lon):
        return False, (
            'Drop location is outside the SaaradhiGo service area. '
            'We currently operate within Hyderabad metro.'
        )
    return True, ''
