# Generated by Django 5.0.3 on 2026-03-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driver_approved'),
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='requested_vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_trips', to='driver.vehicletype'),
        ),
    ]
