# Generated by Django 5.0.3 on 2026-03-13 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_driver_active_vehicle'),
        ('ride', '0002_trip_requested_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user_id', '-requested_at'], name='ride_trip_user_id_2aadc3_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver_id', '-requested_at'], name='ride_trip_driver__a8d508_idx'),
        ),
    ]
