# Generated by Django 5.0.3 on 2026-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_trip_otp_alter_trip_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripstatus',
            name='status_code',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('reached', 'Reached'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, unique=True),
        ),
    ]
