# Generated by Django 5.0.3 on 2026-04-18 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_trip_reached_at_alter_tripstatus_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='ride.tripstatus'),
        ),
        migrations.AlterField(
            model_name='tripstatus',
            name='status_code',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('reached', 'Reached'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('requested', 'Requested')], max_length=20, unique=True),
        ),
    ]
