# Generated by Django 5.0.3 on 2026-04-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_alter_trip_status_id_alter_tripstatus_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='ride.tripstatus'),
        ),
    ]
