# Generated by Django 5.0.3 on 2026-05-15 08:47

import django.db.models.deletion
import servers.ride.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_alter_trip_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status_id',
            field=models.ForeignKey(default=servers.ride.models.get_default_trip_status, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='ride.tripstatus'),
        ),
    ]
