# Generated by Django 5.0.3 on 2026-05-22 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_alter_trip_status_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('payment_status', models.CharField(blank=True, default='', max_length=32)),
                ('sent_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('html_body', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_failure_reason', models.TextField(blank=True, default='')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='ride.trip')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['trip_id', '-version'], name='receipt_trip_ver_idx')],
            },
        ),
    ]
