# Generated by Django 5.0.3 on 2026-05-22 07:01

import base.media
import base.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_ratecard_id_alter_servicezone_code_and_more'),
        ('ride', '0008_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=512, null=True, storage=base.storage_backends.private_document_storage, upload_to=base.media.PrefixedUUIDPath('receipts')),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('flat', 'Flat amount off')], max_length=8)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('max_total_redemptions', models.PositiveIntegerField(blank=True, help_text='None = unlimited globally. The redemption counter is checked atomically before crediting.', null=True)),
                ('max_per_user_redemptions', models.PositiveIntegerField(default=1)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promo_codes', to='pricing.servicezone')),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=256)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='ride.promocode')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to='ride.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('system', 'System')], max_length=8)),
                ('body', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='ride.trip')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trip', 'created_at'], name='chat_trip_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_to'], name='promo_active_window_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['promo', 'user'], name='redeem_promo_user_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['user', '-created_at'], name='redeem_user_recent_idx'),
        ),
    ]
