# Generated by Django 5.0.3 on 2026-07-26 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_driver_fatigue_lockout_until_drivercancellation_and_more'),
        ('pricing', '0004_seed_vja_wgl_vtz'),
        ('ride', '0009_receipt_pdf_file_promocode_promoredemption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Charged to the cancelling party, per the published cancellation policy.', max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('rider', 'Rider'), ('driver', 'Driver'), ('system', 'System / auto'), ('admin', 'Admin')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='trip',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='pricing.servicezone'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status_id', '-requested_at'], name='trip_status_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['zone', '-requested_at'], name='trip_zone_recent_idx'),
        ),
    ]
