# Generated by Django 5.0.3 on 2026-08-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_trip_cancellation_fee_trip_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
