# Generated by Django 5.2.17 on 2026-09-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_driver_doc_rejection_reason'),
        ('ride', '0011_trip_actual_duration_min_trip_estimated_duration_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accuracy_m', models.FloatField(blank=True, help_text='Device-reported horizontal accuracy in metres. Low-accuracy points are dropped by the sampler rather than stored.', null=True)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('driver_ws', 'Driver app websocket ping'), ('driver_rest', 'Driver app REST update'), ('backfill', 'Backfilled / reconstructed')], default='driver_ws', max_length=16)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_location_points', to='driver.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='ride.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'recorded_at'], name='triploc_trip_time_idx'), models.Index(fields=['driver', '-recorded_at'], name='triploc_driver_time_idx'), models.Index(fields=['received_at'], name='triploc_received_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip', 'recorded_at', 'sequence'), name='triploc_no_exact_duplicate')],
            },
        ),
    ]
