# Generated by Django 5.2.17 on 2026-09-24 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0021_driver_doc_rejection_reason'),
        ('pricing', '0006_trip_fare_shadow'),
        ('ride', '0012_triplocationpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='client_request_id',
            field=models.CharField(blank=True, default=None, help_text='Client-generated idempotency key for the booking request. The same value retried returns the original trip.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('user_id', 'client_request_id'), name='trip_unique_client_request_per_rider'),
        ),
    ]
