# Generated by Django 5.2.17 on 2026-09-23 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0013_trip_client_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farepricing',
            name='actual_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='actual_duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='fare_basis',
            field=models.CharField(choices=[('estimate_legacy', 'Estimate (no metering in force)'), ('estimate_no_telemetry', 'Estimate (telemetry unusable)'), ('metered', 'Metered from the trail'), ('metered_degraded', 'Metered, degraded coverage')], default='estimate_legacy', max_length=32),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='gross_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='min_fare_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='night_surge_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='night_surge_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='pricing_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fare_snapshots', to='ride.promocode'),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='quoted_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='quoted_duration_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='rate_card_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='rider_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='snapshot_type',
            field=models.CharField(choices=[('quote', 'Quote at booking'), ('final', 'Final at completion')], db_index=True, default='quote', max_length=8),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='surge_cap_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='vehicle_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='zone_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='farepricing',
            index=models.Index(fields=['trip_id', '-version'], name='farepricing_trip_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='farepricing',
            constraint=models.UniqueConstraint(condition=models.Q(('snapshot_type', 'final')), fields=('trip_id',), name='farepricing_one_final_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='farepricing',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__isnull', True), ('discount_amount__gte', 0), _connector='OR'), name='farepricing_discount_non_negative'),
        ),
    ]
