# Generated by Django 5.2.17 on 2026-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0014_fare_snapshot_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='farepricing',
            name='trail_coverage_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='trail_max_gap_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farepricing',
            name='trail_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
