# Generated by Django 5.2.17 on 2026-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0015_farepricing_trail_coverage_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='last_driver_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Server clock, last time the assigned driver was seen alive on this trip. Written coalesced -- see servers.ride.liveness -- so a 12-ping minute costs one UPDATE, not twelve.', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_rider_activity_at',
            field=models.DateTimeField(blank=True, help_text='Server clock, last time the rider was seen on this trip. Advisory only: a rider whose app is closed must never block the driver from completing a legitimate ride.', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='stale_flagged_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set by the stale-ride detector when a trip stops looking alive. A FLAG, not a decision -- it never changes status. Cleared automatically when activity resumes.', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='stale_reason',
            field=models.CharField(blank=True, default='', help_text='Why the detector flagged this trip, for the operator queue.', max_length=64),
        ),
    ]
